### ISSUE TITLE
Cannot use name_from_serializer

### ISSUE THREAD

**Issue by reinvanimschoot** [ElMassimo/types_from_serializers#17]
[troubleshooting section]: https://types-from-serializers.netlify.app/faqs/

- [X] I have tried upgrading by running `bundle update types_from_serializers`.
- [X]  I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

When using:

```rb
if Rails.env.development?
  TypesFromSerializers.config do |config|
    config.name_from_serializer = ->(name) { name }
  end
end
```
and then issuing the command:

```bundle exec rake types_from_serializers:generate```

no serializers are found

```
bundle exec rake types_from_serializers:generate
Generating TypeScript interfaces...completed in 0.0 seconds.
Found 0 serializers:
```
while, when removing the line `config.name_from_serializer = ->(name) { name }`, everything works as it should.

I only wanted to make sure the generated types got a prefix, which should not interfere with the finding of serializers.

**Comment by reinvanimschoot** [comment]
@ElMassimo without wanting to rush your or whatever, just wanted to know if this library is still supported :)

**Comment by ElMassimo** [comment]
Hi Rein, thanks for reporting.

Can you replicate it in the examples in this repo or provide a minimal reproduction?

**Comment by ElMassimo** [comment]
I could not replicate this, using `config.name_from_serializer = ->(name) { name }` will generate interfaces, with a different name and in different dirs as expected.

Feel free to reopen if you provide a reproduction.
