### ISSUE TITLE
Nested Serializers

### ISSUE THREAD

**Issue by mkdynamic** [ElMassimo/types_from_serializers#19]
Howdy! Given this serializer (in a single file, verbatim):

```ruby
class FooSerializer < BaseSerializer
  class BarSerializer < BaseSerializer
    attributes :id
  end

  belongs_to :bar, serializer: BarSerializer
end
```

The generated TS file is invalid:

```typescript
import type FooSerializerBar from './FooSerializer/Bar'

export default interface Foo {
  bar: FooSerializerBar
}

```

The `./FooSerializer/Bar` does not exist.

Am I doing something wrong, or is this currently unsupported?

I find this pattern of nesting serializers is very useful when you need a representation of a child resource that depends on the parent context vs. having one large serializer in the base directory with a lot of flags/conditionals.

**Comment by ElMassimo** [comment]
Hi Mark! Thanks for reporting!

This is indeed a bug, ideally nested serializers would be included in the same file.

> this pattern of nesting serializers is very useful

Completely agree.

**Comment by ElMassimo** [comment]
Didn't realize until now, but a workaround I was using in my projects is to have it in the same file but with a different name:

```ruby
class FooBarSerializer < BaseSerializer
  attributes :id
end

class FooSerializer < BaseSerializer
  belongs_to :bar, serializer: FooBarSerializer
end
```

However, the nested idiom is better because it avoids polluting the global namespace.

**Comment by rolftimmermans** [comment]
The inline serializers are explicitly removed from the list of serializers to generate interfaces for. Removing this check seems to work? What was the original reason to skip generating types for inline serializers? https://github.com/ElMassimo/types_from_serializers/blob/146ba40bc1a0da37473cd3b705a8ca982c2d173f/types_from_serializers/lib/types_from_serializers/generator.rb#L318

**Comment by ElMassimo** [comment]
> What was the original reason to skip generating types for inline serializers?

The limitation was related to the first implementation, which did not use `listen` to track file changes, so we had less information about which serializers to regenerate.

Now that we detect changed files, we can load those, and ensure any serializers defined inside the file (even inline ones) are regenerated, so it's no longer a dx problem.
